name: Continuos Integration

on:
  push: # Push event
    branches: # On branches 
      - 'releases/**'
      - 'main'
      - 'dev'

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.
      - name: run install, build and test
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@github.com"
          npm install
          npm run test
          npm run lint
          npm run build
